### ISSUE TITLE
Fix use_common_masking_policy_schema_only not creating schema

### ISSUE THREAD

**Issue by thu-IL** [entechlog/dbt-snow-mask#35] opened 2022-06-07 11:59 UTC
I can't use use_common_masking_policy_schema_only without use_common_masking_policy_db
It's not creating the specified common schema

**Comment by entechlog** [comment] 2022-06-07 14:18
@thu-IL , Which version of the package are you using ? Can you make sure it's the latest one ? In the latest model create_masking_policy_schema is set to True by default and should be creating the schema unless you choose to change to false in your project yml file

**Comment by thu-IL** [comment] 2022-06-08 02:28
I'm using 0.2.0 which I believe is the latest version
I'm looking at create_masking_policy macro and it's true that create_masking_policy_schema is defaulted to true but it's put inside an if statement where use_common_masking_policy_db must be true or yes. It means that we have to set a common db to be able to use common schema, which is not what I want

**Comment by entechlog** [comment] 2022-06-08 06:12
@thu-IL , I guess I fixed the issue with release candidate https://github.com/entechlog/dbt-snow-mask/releases/tag/0.2.1rc1

Can you please test and let me know ? This a prerelease so you will have to add the git url to test it 

```
   - git: "https://github.com/entechlog/dbt-snow-mask.git"
     revision: 0.2.1rc1
```

**Comment by thu-IL** [comment] 2022-06-08 07:51
Thanks for the quick fix
It works without having to configure common db. However, I have this line of code in on-run-start and it doesn't run
  - '{{ dbt_snow_mask.create_masking_policy(resource_type=sources)}}'
  
I have to manually create masking policies for sources by 
dbt run-operation create_masking_policy --args '{"resource_type": "sources"}'
--


<br class="Apple-interchange-newline">

**Comment by thu-IL** [comment] 2022-06-09 06:07
[dbt_project_sample.txt](https://github.com/entechlog/dbt-snow-mask/files/8867338/dbt_project_sample.txt)
Hi. This is the yaml file (.txt because it doesn't support .yml). I modified some info because of data protection issue but the configuration related to this package is kept the same.

**Comment by entechlog** [comment] 2022-06-10 05:33
@thu-IL I will check over the weekend and will get back

**Comment by entechlog** [comment] 2022-06-11 09:13
@thu-IL, Did you trying using them as described in the README.md ? create masking policy seems to be working for me using below commands.

```bash
on-run-start:
  - "{{ dbt_snow_mask.create_masking_policy('sources')}}"
 ```

The issue for unapply_masking_policy  has been fixed now, Can you please give it a try using below release candidate ?
https://github.com/entechlog/dbt-snow-mask/releases/tag/0.2.1rc2

**Comment by thu-IL** [comment] 2022-06-13 03:11
Hi @entechlog 
I'm using the same masking policies for models and sources, except they should be created in two different databases. I put them both under on-run-start as you can see in dbt_project file, but not sure why when I run, it only worked for models.
I will test again, for unapply_masking_policy as well and let you know later
For the moment, I have a quite serious problem when running the dbt operation commands in dbt cloud to create and apply masking policies for sources. The job got cancelled automatically and dbt team proactively contacted us saying the package macro is using too much memory. Should I open another issue ticket?
![image](https://user-images.githubusercontent.com/80732061/173272709-2481e854-3760-4663-9a69-afe9eb39c31b.png)

**Comment by nadesansiva** [comment] 2022-06-13 03:17
@thu-IL , 

- I have went a head and released https://github.com/entechlog/dbt-snow-mask/releases/tag/0.2.1 now since it fixed both the issues listed in this ticket. I will wait for you to confirm
- Regarding the memory usage, I am not a dbt cloud user at the moment, So not sure on how to debug that. I suggest to 

1. Upgrade the package to latest version
2. If the issue continues to happen, work with Sara and Team to see if they could help identify the root cause

**Comment by entechlog** [comment] 2022-06-14 20:02
@thu-IL , Just following up to see if you have any updates for me on this one ? Like testing and validating the bug fix and also note on dbt cloud performance?

**Comment by entechlog** [comment] 2022-06-23 15:04
@thu-IL Do you have an update on this ? If I dont hear back, I will go ahead and close this issue today.

**Comment by entechlog** [comment] 2022-06-27 17:50
No response from user, this issue was fixed so closing the issue. Reopen if you feel like this was not addressed

**Closed** 2022-06-27 17:50 UTC
Labels: bug
